# Generated by Django 4.2 on 2023-04-12 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="job",
            fields=[
                (
                    "jid",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("jobTitle", models.CharField(max_length=100)),
                ("jobDesc", models.TextField()),
                (
                    "cid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users.company"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="applied",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("roll_no", models.CharField(max_length=8)),
                ("status", models.CharField(max_length=100)),
                (
                    "jid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="jobs.job"
                    ),
                ),
                (
                    "sid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users.student"
                    ),
                ),
            ],
        ),
    ]
