# Generated by Django 4.2 on 2023-04-14 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_alter_company_minqual"),
        ("jobs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="minQual",
            field=models.ForeignKey(
                default=7.5,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="minQualjob",
                to="users.company",
            ),
        ),
    ]
