# Generated by Django 4.2 on 2023-04-14 07:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0002_job_minqual"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="flag_job",
            field=models.BooleanField(default=False),
        ),
    ]
