# Generated by Django 4.2 on 2023-04-14 07:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0003_job_flag_job"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="job",
            name="minQual",
        ),
    ]
