# Generated by Django 4.2 on 2023-04-14 07:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0004_remove_job_minqual"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="minQual",
            field=models.FloatField(default=7.5),
        ),
    ]
