# Generated by Django 4.2 on 2023-04-14 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0009_alter_alumni_batch_alter_alumni_branch_and_more"),
        ("jobs", "0005_job_minqual"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="applied",
            name="sid",
        ),
        migrations.AlterField(
            model_name="applied",
            name="roll_no",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="roll_noj",
                to="users.student",
            ),
        ),
    ]
