# Generated by Django 4.2 on 2023-04-12 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cid", models.CharField(max_length=100)),
                ("reqCandDet", models.TextField()),
                ("minQual", models.TextField()),
                ("marksCriteria", models.TextField()),
                ("salaryPackage", models.TextField()),
                (
                    "mode_of_interview",
                    models.CharField(
                        choices=[
                            ("Online_written", "Online Written"),
                            ("Offline_written", "Offline Written"),
                            ("Online_interview", "Online Interview"),
                            ("Offine_interview", "Offline Inteview"),
                        ],
                        max_length=50,
                    ),
                ),
                ("time_of_start_iitp", models.TextField()),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("password", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Credits",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("specialization", models.CharField(max_length=100)),
                ("batch", models.CharField(max_length=8)),
                ("credits1", models.IntegerField()),
                ("credits2", models.IntegerField()),
                ("credits3", models.IntegerField()),
                ("credits4", models.IntegerField()),
                ("credits5", models.IntegerField()),
                ("credits6", models.IntegerField()),
                ("credits7", models.IntegerField()),
                ("credits8", models.IntegerField()),
            ],
            options={
                "unique_together": {("specialization", "batch")},
            },
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "roll_no",
                    models.CharField(max_length=8, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("password", models.CharField(max_length=100)),
                ("cgpa", models.FloatField(blank=True)),
                ("areaofInterest", models.TextField(blank=True)),
                ("m10", models.FloatField(blank=True)),
                ("m11", models.FloatField(blank=True)),
                ("m12", models.FloatField(blank=True)),
                ("msem1", models.FloatField(blank=True)),
                ("msem2", models.FloatField(blank=True)),
                ("msem3", models.FloatField(blank=True)),
                ("msem4", models.FloatField(blank=True)),
                ("msem5", models.FloatField(blank=True)),
                ("msem6", models.FloatField(blank=True)),
                ("msem7", models.FloatField(blank=True)),
                ("msem8", models.FloatField(blank=True)),
                ("resume", models.FileField(blank=True, upload_to="resume/")),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="batch_yr",
                        to="users.credits",
                    ),
                ),
                (
                    "specialization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="specialization_branch",
                        to="users.credits",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Alumni",
            fields=[
                ("name", models.CharField(max_length=100)),
                (
                    "rollnumber",
                    models.CharField(max_length=8, primary_key=True, serialize=False),
                ),
                ("email", models.EmailField(max_length=254)),
                ("password", models.CharField(max_length=100)),
                ("batch", models.CharField(max_length=100)),
                ("branch", models.CharField(max_length=100)),
                ("company", models.CharField(max_length=100)),
                ("designation", models.CharField(max_length=100)),
                ("m10", models.FloatField(blank=True)),
                ("m11", models.FloatField(blank=True)),
                ("m12", models.FloatField(blank=True)),
                ("msem1", models.FloatField(blank=True)),
                ("msem2", models.FloatField(blank=True)),
                ("msem3", models.FloatField(blank=True)),
                ("msem4", models.FloatField(blank=True)),
                ("msem5", models.FloatField(blank=True)),
                ("msem6", models.FloatField(blank=True)),
                ("msem7", models.FloatField(blank=True)),
                ("msem8", models.FloatField(blank=True)),
                (
                    "cid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users.company"
                    ),
                ),
            ],
        ),
    ]
