# Generated by Django 4.2 on 2023-04-13 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_remove_student_specialization_alter_student_m10_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="credits",
            name="batch",
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name="credits",
            name="credits1",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="credits",
            name="credits2",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="credits",
            name="credits3",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="credits",
            name="credits4",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="credits",
            name="credits5",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="credits",
            name="credits6",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="credits",
            name="credits7",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="credits",
            name="credits8",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="credits",
            name="specialization",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="student",
            name="areaofInterest",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="student",
            name="batch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="batch_yr",
                to="users.credits",
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="cgpa",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
