# Generated by Django 4.2 on 2023-04-13 18:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_alter_credits_batch_alter_credits_credits1_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="resume",
            field=models.FileField(blank=True, null=True, upload_to="resume/"),
        ),
    ]
