# Generated by Django 4.2 on 2023-04-14 07:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_alter_student_resume"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="minQual",
            field=models.FloatField(default=7.5),
        ),
    ]
