# Generated by Django 4.2 on 2023-04-14 14:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_alter_company_minqual"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="company",
            name="minQual",
        ),
    ]
