# Generated by Django 4.2 on 2023-04-14 14:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_remove_company_minqual"),
    ]

    operations = [
        migrations.RenameField(
            model_name="alumni",
            old_name="rollnumber",
            new_name="roll_no",
        ),
    ]
