# Generated by Django 4.2 on 2023-04-14 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0007_rename_rollnumber_alumni_roll_no"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alumni",
            name="cid",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.company",
            ),
        ),
    ]
