# Generated by Django 4.2 on 2023-04-14 15:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0008_alter_alumni_cid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alumni",
            name="batch",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="alumni",
            name="branch",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="alumni",
            name="company",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="alumni",
            name="designation",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="alumni",
            name="m10",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="alumni",
            name="m11",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="alumni",
            name="m12",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="alumni",
            name="msem1",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="alumni",
            name="msem2",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="alumni",
            name="msem3",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="alumni",
            name="msem4",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="alumni",
            name="msem5",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="alumni",
            name="msem6",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="alumni",
            name="msem7",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="alumni",
            name="msem8",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="alumni",
            name="password",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
