# Generated by Django 4.2 on 2023-04-14 15:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0009_alter_alumni_batch_alter_alumni_branch_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="alumni",
            name="alumprofilepic",
            field=models.ImageField(
                blank=True, null=True, upload_to="alumprofile_pics/"
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="companypic",
            field=models.ImageField(blank=True, null=True, upload_to="company_pics/"),
        ),
        migrations.AddField(
            model_name="student",
            name="studprofilepic",
            field=models.ImageField(
                blank=True, null=True, upload_to="studprofile_pics/"
            ),
        ),
    ]
